#ifndef SMSBARE_BACKEND_RUNTIME_RUNTIME_H
#define SMSBARE_BACKEND_RUNTIME_RUNTIME_H

#include "../core/module.h"
#include "../sms/backend.h"

typedef TSmsCheatLoadStatus BackendCheatLoadStatus;
typedef TSmsCheatPoke BackendCheatPoke;
typedef TSmsCheat BackendCheat;
typedef TSmsCheatGame BackendCheatGame;
typedef TSmsCheatCatalog BackendCheatCatalog;
typedef TSmsMachineProfileSpec BackendMachineProfileSpec;

#define GameMasterLoadOk SmsCheatLoadOk
#define GameMasterLoadFileOpenFailed SmsCheatLoadFileOpenFailed
#define GameMasterLoadCatalogEmpty SmsCheatLoadCatalogEmpty
#define GameMasterLoadLineTooLong SmsCheatLoadLineTooLong
#define GameMasterLoadSyntaxError SmsCheatLoadSyntaxError
#define GameMasterLoadUnexpectedKeyword SmsCheatLoadUnexpectedKeyword
#define GameMasterLoadUnexpectedEnd SmsCheatLoadUnexpectedEnd
#define GameMasterLoadMissingGame SmsCheatLoadMissingGame
#define GameMasterLoadMissingCheat SmsCheatLoadMissingCheat
#define GameMasterLoadDuplicateGame SmsCheatLoadDuplicateGame
#define GameMasterLoadDuplicateCheat SmsCheatLoadDuplicateCheat
#define GameMasterLoadDuplicateRomId SmsCheatLoadDuplicateRomId
#define GameMasterLoadTooManyGames SmsCheatLoadTooManyGames
#define GameMasterLoadTooManyCheats SmsCheatLoadTooManyCheats
#define GameMasterLoadTooManyPokes SmsCheatLoadTooManyPokes
#define GameMasterLoadInvalidHex SmsCheatLoadInvalidHex
#define GameMasterLoadInvalidSize SmsCheatLoadInvalidSize
#define GameMasterLoadValueOutOfRange SmsCheatLoadValueOutOfRange
#define GameMasterLoadTitleTooLong SmsCheatLoadTitleTooLong

typedef SmsBackendVideoHostDebug BackendVideoHostDebug;
typedef SmsBackendAudioStats BackendAudioStats;
typedef SmsBackendAudioMixDebug BackendAudioMixDebug;
typedef SmsBackendAudioChannelDebug BackendAudioChannelDebug;
typedef SmsBackendKeyboardDebug BackendKeyboardDebug;
typedef SmsBackendTimingDebug BackendTimingDebug;
typedef SmsBackendVdpTraceEvent BackendVdpTraceEvent;
typedef SmsBackendVdpTraceView BackendVdpTraceView;
typedef SmsBackendAudioPortTraceEvent BackendAudioPortTraceEvent;
typedef SmsBackendAudioPortTraceView BackendAudioPortTraceView;
typedef SmsBackendKmgTraceEvent BackendKmgTraceEvent;
typedef SmsBackendKmgTraceView BackendKmgTraceView;

enum {
    BACKEND_CAP_STATE = SMS_BACKEND_CAP_STATE,
    BACKEND_CAP_MACHINE = SMS_BACKEND_CAP_MACHINE,
    BACKEND_CAP_MEDIA = SMS_BACKEND_CAP_MEDIA,
    BACKEND_CAP_CHEAT = SMS_BACKEND_CAP_CHEAT,
    BACKEND_CAP_DEBUG = SMS_BACKEND_CAP_DEBUG
};

enum {
    BACKEND_MACHINE_PROFILE_0 = 0u,
    BACKEND_MACHINE_PROFILE_1 = 0u,
    BACKEND_MACHINE_PROFILE_2 = 0u
};

enum {
    BACKEND_VDP_TRACE_NONE = SMS_VDP_TRACE_NONE,
    BACKEND_VDP_TRACE_TITLE = SMS_VDP_TRACE_TITLE,
    BACKEND_VDP_TRACE_SAVE_SELECT = SMS_VDP_TRACE_SAVE_SELECT,
    BACKEND_VDP_TRACE_STARDATE = SMS_VDP_TRACE_STARDATE,
    BACKEND_VDP_TRACE_KMG = SMS_VDP_TRACE_KMG
};

enum {
    BACKEND_VDP_EVENT_NONE = SMS_VDP_EVENT_NONE,
    BACKEND_VDP_EVENT_IE0_FIRE = SMS_VDP_EVENT_IE0_FIRE,
    BACKEND_VDP_EVENT_IE1_ARM = SMS_VDP_EVENT_IE1_ARM,
    BACKEND_VDP_EVENT_IE1_FIRE = SMS_VDP_EVENT_IE1_FIRE,
    BACKEND_VDP_EVENT_R19_WRITE = SMS_VDP_EVENT_R19_WRITE,
    BACKEND_VDP_EVENT_R23_WRITE = SMS_VDP_EVENT_R23_WRITE,
    BACKEND_VDP_EVENT_S1_READ = SMS_VDP_EVENT_S1_READ,
    BACKEND_VDP_EVENT_S2_READ = SMS_VDP_EVENT_S2_READ,
    BACKEND_VDP_EVENT_CMD_START = SMS_VDP_EVENT_CMD_START,
    BACKEND_VDP_EVENT_CMD_END = SMS_VDP_EVENT_CMD_END,
    BACKEND_VDP_EVENT_PORT98_WRITE = SMS_VDP_EVENT_PORT98_WRITE,
    BACKEND_VDP_EVENT_PORT99_ADDR = SMS_VDP_EVENT_PORT99_ADDR,
    BACKEND_VDP_EVENT_PORT99_REG = SMS_VDP_EVENT_PORT99_REG
};

#define BACKEND_CHEAT_CATALOG_PATH SMS_CHEAT_CATALOG_PATH
#define BACKEND_CHEATS_ROOT SMS_CHEATS_ROOT
#define BACKEND_CHEAT_MAX_GAMES SMS_CHEAT_MAX_GAMES
#define BACKEND_CHEAT_MAX_CHEATS SMS_CHEAT_MAX_CHEATS
#define BACKEND_CHEAT_MAX_POKES SMS_CHEAT_MAX_POKES

#define backend_runtime_family_id sms_backend_family_id
#define backend_runtime_default_id sms_backend_default_id
#define backend_runtime_set_requested_backend_id sms_backend_set_requested_backend_id
#define backend_runtime_requested_backend_id sms_backend_requested_backend_id
#define backend_runtime_selected_backend_id sms_backend_selected_backend_id
#define backend_runtime_is_capability_available sms_backend_is_capability_available
#define backend_runtime_init sms_backend_init
#define backend_runtime_reset sms_backend_reset
#define backend_runtime_step_frame sms_backend_step_frame
#define backend_runtime_shutdown sms_backend_shutdown
#define backend_runtime_video_frame sms_backend_video_frame
#define backend_runtime_get_video_presentation sms_backend_get_video_presentation
#define backend_runtime_audio_pull sms_backend_audio_pull
#define backend_runtime_input_push_joystick sms_backend_input_push_joystick
#define backend_runtime_input_push_keyboard sms_backend_input_push_keyboard
#define backend_runtime_media_load_cartridge sms_backend_media_load_cartridge
#define backend_runtime_media_load_disk sms_backend_media_load_disk
#define backend_runtime_media_load_cassette sms_backend_media_load_cassette
#define backend_runtime_get_status sms_backend_get_status
#define backend_runtime_get_info sms_backend_get_info
#define backend_runtime_reboot_basic sms_backend_reboot_basic
#define backend_runtime_menu_reset sms_backend_menu_reset
#define backend_runtime_save_state sms_backend_save_state
#define backend_runtime_load_state sms_backend_load_state
#define backend_runtime_set_overscan sms_backend_set_overscan
#define backend_runtime_set_refresh_hz sms_backend_set_refresh_hz
#define backend_runtime_get_refresh_hz sms_backend_get_refresh_hz
#define backend_runtime_get_frame_interval_us_exact sms_backend_get_frame_interval_us_exact
#define backend_runtime_set_disk_rom_enabled sms_backend_set_disk_rom_enabled
#define backend_runtime_get_disk_rom_enabled sms_backend_get_disk_rom_enabled
#define backend_runtime_set_color_artifacts_enabled sms_backend_set_color_artifacts_enabled
#define backend_runtime_get_color_artifacts_enabled sms_backend_get_color_artifacts_enabled
#define backend_runtime_set_gfx9000_enabled sms_backend_set_gfx9000_enabled
#define backend_runtime_get_gfx9000_enabled sms_backend_get_gfx9000_enabled
#define backend_runtime_set_boot_mode sms_backend_set_boot_mode
#define backend_runtime_get_boot_mode sms_backend_get_boot_mode
#define backend_runtime_get_active_boot_mode sms_backend_get_active_boot_mode
#define backend_runtime_set_model_profile sms_backend_set_model_profile
#define backend_runtime_get_model_profile sms_backend_get_model_profile
#define backend_runtime_get_active_model_profile sms_backend_get_active_model_profile
#define backend_runtime_set_processor_mode sms_backend_set_processor_mode
#define backend_runtime_get_processor_mode sms_backend_get_processor_mode
#define backend_runtime_get_active_processor_mode sms_backend_get_active_processor_mode
#define backend_runtime_set_rammapper_kb sms_backend_set_rammapper_kb
#define backend_runtime_get_rammapper_kb sms_backend_get_rammapper_kb
#define backend_runtime_set_megaram_kb sms_backend_set_megaram_kb
#define backend_runtime_get_megaram_kb sms_backend_get_megaram_kb
#define backend_runtime_set_z80_turbo_mode sms_backend_set_z80_turbo_mode
#define backend_runtime_get_z80_turbo_mode sms_backend_get_z80_turbo_mode
#define backend_runtime_set_fm_music_enabled sms_backend_set_fm_music_enabled
#define backend_runtime_get_fm_music_enabled sms_backend_get_fm_music_enabled
#define backend_runtime_set_scc_plus_enabled sms_backend_set_scc_plus_enabled
#define backend_runtime_get_scc_plus_enabled sms_backend_get_scc_plus_enabled
#define backend_runtime_set_scc_dual_cart_enabled sms_backend_set_scc_dual_cart_enabled
#define backend_runtime_get_scc_dual_cart_enabled sms_backend_get_scc_dual_cart_enabled
#define backend_runtime_get_scc_dual_cart_available sms_backend_get_scc_dual_cart_available
#define backend_runtime_set_fm_layer_gain_pct sms_backend_set_fm_layer_gain_pct
#define backend_runtime_get_fm_layer_gain_pct sms_backend_get_fm_layer_gain_pct
#define backend_runtime_set_audio_layer_muted sms_backend_set_audio_layer_muted
#define backend_runtime_get_audio_layer_muted sms_backend_get_audio_layer_muted
#define backend_runtime_get_psg_mixer_reg7 sms_backend_get_psg_mixer_reg7
#define backend_runtime_get_master_switch sms_backend_get_master_switch
#define backend_runtime_set_frame_perf_telemetry_enabled sms_backend_set_frame_perf_telemetry_enabled
#define backend_runtime_reset_audio_mix_debug_window sms_backend_reset_audio_mix_debug_window
#define backend_runtime_get_cartridge_name sms_backend_get_cartridge_name
#define backend_runtime_get_disk_name sms_backend_get_disk_name
#define backend_runtime_get_cassette_name sms_backend_get_cassette_name
#define backend_runtime_get_cartridge_path sms_backend_get_cartridge_path
#define backend_runtime_get_disk_path sms_backend_get_disk_path
#define backend_runtime_get_cassette_path sms_backend_get_cassette_path
#define backend_runtime_set_cartridge_path sms_backend_set_cartridge_path
#define backend_runtime_set_disk_path sms_backend_set_disk_path
#define backend_runtime_set_cassette_path sms_backend_set_cassette_path
#define backend_runtime_unload_cartridge sms_backend_unload_cartridge
#define backend_runtime_unload_disk sms_backend_unload_disk
#define backend_runtime_unload_cassette sms_backend_unload_cassette
#define backend_runtime_reset_cheat_session sms_backend_reset_cheat_session
#define backend_runtime_set_cheat_enabled sms_backend_set_cheat_enabled
#define backend_runtime_set_cheat_value sms_backend_set_cheat_value
#define backend_runtime_is_cheat_active sms_backend_is_cheat_active
#define backend_runtime_reset_game_master_session sms_backend_reset_cheat_session
#define backend_runtime_set_game_master_cheat_enabled sms_backend_set_cheat_enabled
#define backend_runtime_set_game_master_cheat_value sms_backend_set_cheat_value
#define backend_runtime_is_game_master_cheat_active sms_backend_is_cheat_active
#define backend_runtime_peek8 sms_backend_peek8
#define backend_runtime_peek16 sms_backend_peek16
#define backend_runtime_set_load_diag sms_backend_set_load_diag
#define backend_runtime_get_load_diag sms_backend_get_load_diag
#define backend_runtime_get_video_host_debug sms_backend_get_video_host_debug
#define backend_runtime_get_audio_stats sms_backend_get_audio_stats
#define backend_runtime_get_audio_mix_debug sms_backend_get_audio_mix_debug
#define backend_runtime_get_audio_channel_debug sms_backend_get_audio_channel_debug
#define backend_runtime_get_keyboard_debug sms_backend_get_keyboard_debug
#define backend_runtime_get_timing_debug sms_backend_get_timing_debug
#define backend_runtime_get_vdp_trace_view sms_backend_get_vdp_trace_view
#define backend_runtime_get_audio_port_trace_view sms_backend_get_audio_port_trace_view
#define backend_runtime_get_kmg_trace_view sms_backend_get_kmg_trace_view
#define backend_runtime_initramfs_mount sms_initramfs_mount
#define backend_runtime_initramfs_mount_boot_minimal sms_initramfs_mount_boot_minimal
#define backend_runtime_initramfs_mount_remaining sms_initramfs_mount_remaining
#define backend_runtime_initramfs_files_mounted sms_initramfs_files_mounted
#define backend_runtime_initramfs_source sms_initramfs_source
#define backend_runtime_initramfs_bytes sms_initramfs_bytes
#define backend_cheat_catalog_reset sms_cheat_catalog_reset
#define backend_cheat_catalog_load sms_cheat_catalog_load
#define backend_cheat_catalog_load_default sms_cheat_catalog_load_default
#define backend_cheat_catalog_load_mcf sms_cheat_catalog_load_mcf
#define backend_cheat_catalog_status_name sms_cheat_catalog_status_name
#define backend_machine_profile_count sms_machine_profile_count
#define backend_machine_profile_clamp sms_machine_profile_clamp
#define backend_machine_profile_get sms_machine_profile_get
#define backend_machine_profile_default sms_machine_profile_default
#define backend_machine_profile_label sms_machine_profile_label
#define backend_machine_profile_is_sms_family sms_machine_profile_is_sms_family

#endif
