#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -ne 1 ]; then
  echo "Uso: $0 <saida-header>" >&2
  exit 1
fi

OUT_FILE="$1"
OUT_DIR="$(dirname "$OUT_FILE")"
mkdir -p "$OUT_DIR"

num_or_default() {
  local value="$1"
  local fallback="$2"
  case "$value" in
    0|1|2)
      printf '%s' "$value"
      ;;
    *)
      printf '%s' "$fallback"
      ;;
  esac
}

SMSBARE_BOOT_MODE_DEFAULT_ENUM="$(num_or_default "${SMSBARE_BOOT_MODE_DEFAULT_ENUM:-0}" 0)"
SMSBARE_BOOT_MODE_LOCKED="$(num_or_default "${SMSBARE_BOOT_MODE_LOCKED:-0}" 0)"
SMSBARE_BOOT_MODE_DEFAULT="${SMSBARE_BOOT_MODE_DEFAULT:-NORM}"
SMSBARE_PATREON_TAG="${SMSBARE_PATREON_TAG:-}"

cat > "$OUT_FILE" <<HEADER
#ifndef SMSBARE_BUILD_CONFIG_H
#define SMSBARE_BUILD_CONFIG_H

/* Auto-generated by scripts/gen-build-header.sh */
#define SMSBARE_BOOT_MODE_DEFAULT_ENUM ${SMSBARE_BOOT_MODE_DEFAULT_ENUM}
#define SMSBARE_BOOT_MODE_LOCKED ${SMSBARE_BOOT_MODE_LOCKED}
#define SMSBARE_BOOT_MODE_DEFAULT "${SMSBARE_BOOT_MODE_DEFAULT}"
#define SMSBARE_PATREON_TAG "${SMSBARE_PATREON_TAG}"

#endif /* SMSBARE_BUILD_CONFIG_H */
HEADER

echo "Gerado: $OUT_FILE"
