#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

CONFIG_KCONFIG_FILE="$ROOT_DIR/.config"
CONFIG_ROOT_MK_FILE="$ROOT_DIR/.config.mk"
CONFIG_BUILD_MK_FILE="$ROOT_DIR/build/config.mk"
KCONFIG_SPEC_FILE="$ROOT_DIR/config/Kconfig.smsbarepi"
MCONF_BIN="$ROOT_DIR/build/tools/kconfig-linux/mconf"
MCONF_SAVED_MARKER="$ROOT_DIR/build/tools/kconfig-linux/.menuconfig.saved"
SYNC_ONLY=0

if [ "${1:-}" = "--sync-only" ]; then
  SYNC_ONLY=1
  shift
fi

kconfig_enabled() {
  local key="$1"
  if grep -Eq "^CONFIG_${key}=y$" "$CONFIG_KCONFIG_FILE" 2>/dev/null; then
    echo 1
  else
    echo 0
  fi
}

kconfig_string() {
  local key="$1"
  local line
  line=$(grep -E "^CONFIG_${key}=\"" "$CONFIG_KCONFIG_FILE" 2>/dev/null || true)
  line="${line#*=}"
  line="${line#\"}"
  line="${line%\"}"
  printf '%s' "$line"
}

ensure_default_kconfig() {
  cat > "$CONFIG_KCONFIG_FILE" <<'KCONF'
# Auto-generated baseline config for SMSBarePI
CONFIG_SMSBARE_DEBUG=y
# CONFIG_SMSBARE_BOOT_MODE_NONE is not set
CONFIG_SMSBARE_BOOT_MODE_NORM=y
# CONFIG_SMSBARE_BOOT_MODE_FAST is not set
# CONFIG_SMSBARE_BOOT_MODE_GAME is not set
CONFIG_SMSBARE_PATREON_TAG=""
KCONF
}

prepare_kconfig_file() {
  if [ ! -f "$CONFIG_KCONFIG_FILE" ]; then
    if [ "${INTERACTIVE_MODE:-0}" = "1" ]; then
      return 0
    fi
    ensure_default_kconfig
    return 0
  fi

  if grep -q '^CONFIG_SMSBARE_' "$CONFIG_KCONFIG_FILE"; then
    return 0
  fi

  ensure_default_kconfig
}

emit_make_config() {
  mkdir -p "$ROOT_DIR/build"

  local DEBUG
  local SMSBARE_PATREON_TAG
  local SMSBARE_BOOT_MODE_DEFAULT

  DEBUG="$(kconfig_enabled SMSBARE_DEBUG)"
  SMSBARE_PATREON_TAG="$(kconfig_string SMSBARE_PATREON_TAG)"

  if [ "$(kconfig_enabled SMSBARE_BOOT_MODE_NONE)" = "1" ]; then
    SMSBARE_BOOT_MODE_DEFAULT="NONE"
  elif [ "$(kconfig_enabled SMSBARE_BOOT_MODE_FAST)" = "1" ]; then
    SMSBARE_BOOT_MODE_DEFAULT="FAST"
  elif [ "$(kconfig_enabled SMSBARE_BOOT_MODE_GAME)" = "1" ]; then
    SMSBARE_BOOT_MODE_DEFAULT="GAME"
  else
    SMSBARE_BOOT_MODE_DEFAULT="NORM"
  fi

  {
    echo "# Auto-generated by scripts/menuconfig.sh"
    echo "DEBUG_CONFIG := $DEBUG"
    echo "DEBUG := $DEBUG"
    echo "SMSBARE_BOOT_MODE_DEFAULT_CONFIG := $SMSBARE_BOOT_MODE_DEFAULT"
    echo "SMSBARE_BOOT_MODE_DEFAULT := $SMSBARE_BOOT_MODE_DEFAULT"
    echo "SMSBARE_PATREON_TAG_CONFIG := $SMSBARE_PATREON_TAG"
    echo "SMSBARE_PATREON_TAG := $SMSBARE_PATREON_TAG"
  } > "$CONFIG_ROOT_MK_FILE"

  cp "$CONFIG_ROOT_MK_FILE" "$CONFIG_BUILD_MK_FILE"

  echo "Gerado/atualizado: .config"
  echo "Gerado: .config.mk"
  echo "Gerado: build/config.mk"
}

INTERACTIVE_MODE=0
if [ "$SYNC_ONLY" = "0" ] && [ "${NON_INTERACTIVE:-0}" != "1" ] && [ -t 0 ] && [ -t 1 ]; then
  INTERACTIVE_MODE=1
fi

prepare_kconfig_file

if [ "$INTERACTIVE_MODE" = "1" ]; then
  if [ ! -x "$MCONF_BIN" ] \
    || [ "$ROOT_DIR/tools/kconfig-linux/mconf.c" -nt "$MCONF_BIN" ] \
    || [ "$ROOT_DIR/tools/kconfig-linux/lxdialog/util.c" -nt "$MCONF_BIN" ]; then
    ./scripts/build-kconfig-mconf.sh
  fi

  rm -f "$MCONF_SAVED_MARKER"
  export KCONFIG_CONFIG="$CONFIG_KCONFIG_FILE"
  export MCONF_SAVED_MARKER
  "$MCONF_BIN" "$KCONFIG_SPEC_FILE"
fi

if [ "$INTERACTIVE_MODE" = "1" ]; then
  if [ -f "$MCONF_SAVED_MARKER" ]; then
    emit_make_config
  fi
else
  emit_make_config
fi
